### ISSUE TITLE
App Crash on Opening Attached File

### ISSUE THREAD

**Issue by CodeNomadHQ** [PhilKes/NotallyX#11]
The app crashes when opening an attached file.

### Showcase 
https://github.com/user-attachments/assets/3b48d7ef-3f26-4440-af0e-f9ca9dbd0f6f

### Log
```
package: com.omgodse.notally:56
process: com.omgodse.notally
processUptime: 4206 + 115 ms
installer: com.android.packageinstaller
 
android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.VIEW dat=content://com.omgodse.notally.provider/... typ=application/zip flg=0x1 }
at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2441)
at android.app.Instrumentation.execStartActivity(Instrumentation.java:2011)
at android.app.Activity.startActivityForResult(Activity.java:5886)
at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.java:597)
at android.app.Activity.startActivityForResult(Activity.java:5806)
at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.java:583)
at android.app.Activity.startActivity(Activity.java:6348)
at android.app.Activity.startActivity(Activity.java:6315)
at com.omgodse.notally.activities.NotallyActivity$setupFiles$adapter$1.invoke(NotallyActivity.kt:441)
at com.omgodse.notally.activities.NotallyActivity$setupFiles$adapter$1.invoke(NotallyActivity.kt:424)
at com.omgodse.notally.recyclerview.adapter.PreviewFileAdapter$onCreateViewHolder$1.invoke(PreviewFileAdapter.kt:24)
at com.omgodse.notally.recyclerview.adapter.PreviewFileAdapter$onCreateViewHolder$1.invoke(PreviewFileAdapter.kt:24)
at com.omgodse.notally.recyclerview.viewholder.PreviewFileVH._init_$lambda$0(PreviewFileVH.kt:15)
at com.omgodse.notally.recyclerview.viewholder.PreviewFileVH.$r8$lambda$KEJdawB3svmP3V1FA8C0RbxDqGo(Unknown Source:0)
at com.omgodse.notally.recyclerview.viewholder.PreviewFileVH$$ExternalSyntheticLambda0.onClick(D8$$SyntheticClass:0)
at android.view.View.performClick(View.java:7931)
at android.widget.CompoundButton.performClick(CompoundButton.java:146)
at android.view.View.performClickInternal(View.java:7908)
at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
at android.view.View$PerformClick.run(View.java:30990)
at android.os.Handler.handleCallback(Handler.java:959)
at android.os.Handler.dispatchMessage(Handler.java:100)
at android.os.Looper.loopOnce(Looper.java:232)
at android.os.Looper.loop(Looper.java:317)
at android.app.ActivityThread.main(ActivityThread.java:8623)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:894)
```

**Comment by PhilKes** [comment]
> You attached a zip file. Do you have any apps installed that can handle zip files?

Looks like the behaviour of `startActivity()` is to throw a `ActivityNotFoundException` if there is not suitable app installed
