### ISSUE TITLE
Biometric Lock crash

### ISSUE THREAD

**Issue by RahulxPaul** [PhilKes/NotallyX#177]
### What happened?

A bug happened!
Having set biomatric lock app started crashing

### App Version

6.3.0

### Android Version

31

### (Optional) Relevant log output

```shell
java.lang.RuntimeException: Exception while computing database live data.at androidx.room.v.run(SourceFile:274)at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)at java.lang.Thread.run(Thread.java:920)Caused by: net.sqlcipher.database.SQLiteException: file is not a database: , while compiling: select count(*) from sqlite_master
```

**Comment by PranshulGG** [comment]
@RahulxPaul, it looks like there might be a small mistake, there isn't an Android version 31

**Comment by PhilKes** [comment]
> @RahulxPaul, it looks like there might be a small mistake, there isn't an Android version 31

Android Version refers to the SDK/API-Level, you can find the version matrix at e.g. https://apilevels.com/
31 -> Android 12

**Comment by RahulxPaul** [comment]
Its android 13

**Comment by PranshulGG** [comment]
> Its android 13

Have you tried clearing the app data?

**Comment by RahulxPaul** [comment]
Yes twice but didn't work

**Comment by PhilKes** [comment]
@RahulxPaul can you try again with the latest version [6.4.1](https://github.com/PhilKes/NotallyX/releases/tag/v6.4.1) to see if this issue still remains?
